sut:
  build: .
  command:
    - sh
    - -xc
    - |
      /home/linuxbrew/.linuxbrew/bin/brew test-bot
      status=$$?
      exit $$status
  environment:
    # GitHub Actions
    - GITHUB_ACTIONS
    - GITHUB_BASE_REF
    - GITHUB_EVENT_NAME
    - GITHUB_REF
    - GITHUB_REPOSITORY
    - GITHUB_SHA
    - GITHUB_WORKSPACE
    - HEAD_GITHUB_REF
