version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:stretch

    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: Setup Homebrew
          command: |
            set -x
            HOMEBREW_REPOSITORY=/home/linuxbrew/.linuxbrew
            sudo mkdir -p /home/linuxbrew
            sudo git clone https://github.com/Homebrew/brew "$HOMEBREW_REPOSITORY"
            sudo mkdir -p "$HOMEBREW_REPOSITORY/Library/Taps/homebrew"
            sudo ln -s "$PWD" "$HOMEBREW_REPOSITORY/Library/Taps/homebrew/homebrew-test-bot"
            sudo chown -R "$USER" /home/linuxbrew
            sudo locale-gen en_US.UTF-8
            sudo dpkg-reconfigure locales
            sudo bash -c "echo LANG=en_US.UTF-8 > /etc/environment"
            sudo bash -c "echo LANG=en_US.UTF-8 > /etc/default/locale"
            export PATH="$HOMEBREW_REPOSITORY/bin:/usr/bin:/bin"
            ls -lha /home/linuxbrew
            ls -lha /home/linuxbrew/.linuxbrew
            # trigger vendored ruby installation
            brew help

      - run:
          name: Run brew test-bot
          command: brew test-bot
